/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package granjero;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AnToNiO
 */
public class escenario extends javax.swing.JFrame {
public persona persona1 = new persona();
public ArrayList cosasLlevadas = new ArrayList();
public ArrayList cosasDejadas = new ArrayList();
 
    /**
     * Creates new form escenario
     */
    public escenario() {
        initComponents();
        fondo fon= new fondo();
        Instruccion ini = new Instruccion(this, true);
        ini.setVisible(true);
        this.setLocationRelativeTo(null);
        this.add(fon, BorderLayout.CENTER);
        this.pack();
        
        cosasDejadas.add("gallina");
        cosasDejadas.add("lobo");
        cosasDejadas.add("maiz");
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gallina = new javax.swing.JButton();
        maiz = new javax.swing.JButton();
        bote = new javax.swing.JButton();
        lobo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 255, 0));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setPreferredSize(new java.awt.Dimension(680, 450));
        setResizable(false);

        jLabel1.setText("COMENCEMOS EL JUEGO!!");

        nuevo.setBackground(new java.awt.Color(255, 204, 51));
        nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 102, 102));
        nuevo.setText("Juego Nuevo");
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nuevo))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gallina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g.png"))); // NOI18N
        gallina.setAlignmentX(getAlignmentX());
        gallina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gallinaMouseClicked(evt);
            }
        });

        maiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/m.png"))); // NOI18N
        maiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maizMouseClicked(evt);
            }
        });

        bote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.png"))); // NOI18N
        bote.setToolTipText("");
        bote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boteMouseClicked(evt);
            }
        });

        lobo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/l.PNG"))); // NOI18N
        lobo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loboMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1021, 1021, 1021)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lobo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gallina, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(bote, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(maiz, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lobo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(gallina, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maiz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(bote)))
                .addGap(401, 401, 401)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gallinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallinaMouseClicked
   
      
        if(gallina.getBounds().x==600&&bote.getBounds().x==450){
            persona1.regresarGallina(true, this);
            
        }else if(gallina.getBounds().x==600&&bote.getBounds().x!=450){
             JOptionPane.showMessageDialog( null, "Regrese el bote","INVALIDO", JOptionPane.INFORMATION_MESSAGE );
        }else if(cosasLlevadas.contains("lobo")&&cosasLlevadas.contains("maiz")&&
                cosasDejadas.contains("gallina")&&bote.getBounds().x==150){
         
            persona1.llevarGallina(true, this);
            cosasDejadas.remove("gallina");
            cosasLlevadas.add("gallina");
             JOptionPane.showMessageDialog( null, "FELICIDADES. HAS GANADO","FIN DEL JUEGO", JOptionPane.INFORMATION_MESSAGE );
        }
        
        else{
        
        
        persona1.llevarGallina(true, this);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_gallinaMouseClicked

    private void boteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boteMouseClicked
       if(bote.getBounds().x==450){
           persona1.regresar(true,this);
          
            
        }else{persona1.llevar(this);}
       

        // TODO add your handling code here:
    }//GEN-LAST:event_boteMouseClicked

    private void maizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maizMouseClicked
        if(maiz.getBounds().x==600&&bote.getBounds().x==450){
            persona1.regresarMaiz(true, this);
            
        }else if(maiz.getBounds().x==600&&bote.getBounds().x!=450){
             JOptionPane.showMessageDialog( null, "Regrese el bote", "INVALIDO",JOptionPane.INFORMATION_MESSAGE );
        }else{
        
        if(cosasLlevadas.contains("gallina")&&cosasDejadas.contains("lobo")){
            
            
            if(bote.getBounds().x!=450){
             persona1.llevarMaiz(true, this);
            }else{JOptionPane.showMessageDialog( null,"Regrese el bote","INVALIDO", JOptionPane.INFORMATION_MESSAGE );}
           
           
            
        }else if(cosasLlevadas.contains("lobo")&&cosasLlevadas.contains("maiz")){
            persona1.llevarMaiz(true, this);
            persona1.llevar(this);
        }else if(cosasDejadas.contains("lobo")){
            
             persona1.llevarMaiz(true, this);}
      else if(cosasDejadas.contains("lobo")&&cosasDejadas.contains("gallina")){
         // JOptionPane.showMessageDialog( null,"El lobo se comio a la gallina","Game over", JOptionPane.INFORMATION_MESSAGE );}    
      }}
    
                // TODO add your handling code here:
    }//GEN-LAST:event_maizMouseClicked

    private void loboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loboMouseClicked
          persona.llevarLobo(true,this);




        // TODO add your handling code here:
    }//GEN-LAST:event_loboMouseClicked

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        escenario nuevo= new escenario();
        nuevo.setVisible(true);
        this.dispose();
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escenario().setVisible(true);
                
            }
        });
        
      
        
        
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bote;
    public static javax.swing.JButton gallina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton lobo;
    public static javax.swing.JButton maiz;
    private javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
